baseURL = "https://refun.js.org/"
languageCode = "zh-CN"
title = "Refun"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = "Refun"
[params]
  author = "Gears"
  description = "Refun 个人网址导航站"
